DROP TABLE IF EXISTS  entry_group;
DROP TABLE IF EXISTS  agreement_forms; 
DROP TABLE IF EXISTS  accounts;
DROP TABLE IF EXISTS  users;
DROP TABLE IF EXISTS  entry_items;
DROP TABLE IF EXISTS  products;
DROP TABLE IF EXISTS  sessions;
