// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: entry_group.sql

package db

import (
	"context"

	zero "gopkg.in/guregu/null.v4/zero"
)

const createEntryGroup = `-- name: CreateEntryGroup :one
INSERT INTO entry_group (
  quantity,
  action_type,
  pricing_type,
  price,
  currency,
  entry_group_status
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
) RETURNING id, quantity, action_type, pricing_type, price, currency, entry_group_status, created_at, updated_at, deleted_at
`

type CreateEntryGroupParams struct {
	Quantity         int32            `json:"quantity"`
	ActionType       ActionType       `json:"action_type"`
	PricingType      PricingType      `json:"pricing_type"`
	Price            float64          `json:"price"`
	Currency         CurrencyCode     `json:"currency"`
	EntryGroupStatus EntryGroupStatus `json:"entry_group_status"`
}

func (q *Queries) CreateEntryGroup(ctx context.Context, arg CreateEntryGroupParams) (EntryGroup, error) {
	row := q.db.QueryRow(ctx, createEntryGroup,
		arg.Quantity,
		arg.ActionType,
		arg.PricingType,
		arg.Price,
		arg.Currency,
		arg.EntryGroupStatus,
	)
	var i EntryGroup
	err := row.Scan(
		&i.ID,
		&i.Quantity,
		&i.ActionType,
		&i.PricingType,
		&i.Price,
		&i.Currency,
		&i.EntryGroupStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteEntryGroup = `-- name: DeleteEntryGroup :exec
DELETE FROM entry_group
WHERE id = $1
`

func (q *Queries) DeleteEntryGroup(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteEntryGroup, id)
	return err
}

const getEntryGroup = `-- name: GetEntryGroup :one
SELECT id, quantity, action_type, pricing_type, price, currency, entry_group_status, created_at, updated_at, deleted_at 
FROM entry_group
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetEntryGroup(ctx context.Context, id int32) (EntryGroup, error) {
	row := q.db.QueryRow(ctx, getEntryGroup, id)
	var i EntryGroup
	err := row.Scan(
		&i.ID,
		&i.Quantity,
		&i.ActionType,
		&i.PricingType,
		&i.Price,
		&i.Currency,
		&i.EntryGroupStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listEntryGroups = `-- name: ListEntryGroups :many
SELECT id, quantity, action_type, pricing_type, price, currency, entry_group_status, created_at, updated_at, deleted_at 
FROM entry_group
ORDER BY id DESC
LIMIT $2
OFFSET $1
`

type ListEntryGroupsParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListEntryGroups(ctx context.Context, arg ListEntryGroupsParams) ([]EntryGroup, error) {
	rows, err := q.db.Query(ctx, listEntryGroups, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntryGroup
	for rows.Next() {
		var i EntryGroup
		if err := rows.Scan(
			&i.ID,
			&i.Quantity,
			&i.ActionType,
			&i.PricingType,
			&i.Price,
			&i.Currency,
			&i.EntryGroupStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntryGroup = `-- name: UpdateEntryGroup :one
UPDATE entry_group
SET 
quantity = COALESCE($1, quantity),
action_type = COALESCE($2, action_type),
pricing_type = COALESCE($3, pricing_type),
price = COALESCE($4, price),
currency = COALESCE($5, currency),
entry_group_status = COALESCE($6, entry_group_status)
WHERE id = $7
RETURNING id, quantity, action_type, pricing_type, price, currency, entry_group_status, created_at, updated_at, deleted_at
`

type UpdateEntryGroupParams struct {
	Quantity         zero.Int    `json:"quantity"`
	ActionType       zero.String `json:"action_type"`
	PricingType      zero.String `json:"pricing_type"`
	Price            zero.Float  `json:"price"`
	Currency         zero.String `json:"currency"`
	EntryGroupStatus zero.String `json:"entry_group_status"`
	ID               int32       `json:"id"`
}

func (q *Queries) UpdateEntryGroup(ctx context.Context, arg UpdateEntryGroupParams) (EntryGroup, error) {
	row := q.db.QueryRow(ctx, updateEntryGroup,
		arg.Quantity,
		arg.ActionType,
		arg.PricingType,
		arg.Price,
		arg.Currency,
		arg.EntryGroupStatus,
		arg.ID,
	)
	var i EntryGroup
	err := row.Scan(
		&i.ID,
		&i.Quantity,
		&i.ActionType,
		&i.PricingType,
		&i.Price,
		&i.Currency,
		&i.EntryGroupStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
